using System;
using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliant(true)]
[assembly: AssemblyVersionAttribute("1.0.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: AssemblyCopyrightAttribute("Copyright Paul Knopf 2014-2014")]
[assembly: AssemblyProductAttribute("SourceIndexingSharp")]
[assembly: AssemblyTrademarkAttribute("SourceIndexingSharp")]
[assembly: AssemblyCompanyAttribute("")]
[assembly: AssemblyConfigurationAttribute("Debug")]
[assembly: AssemblyInformationalVersionAttribute("Debug")]
